ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:checkedbox: pass:normal[{startsb}&#10004;{endsb}]

= Pivotal Cloud Native Applications Workshop

== Overview

[.lead]
This workshop provides developers with hands on experience building cloud native applications with micro service architectures using Spring Boot and Spring Cloud.  Included are presentations, demos and hands on labs.

== Sessions

IMPORTANT: Each new lab exercise builds upon the preceding lab, so please do not skip around the labs!

* Session 1: link:presentations/Session_1_CN_Design_DDD.pptx[_Cloud Native Design, Domain Driven Design, & Microservices_]
* Session 2: link:presentations/Session_2_Intro_Boot.pptx[_Introducing Spring Boot_]
** Lab 1: link:labs/lab01/lab01.adoc[Building A Spring Boot Application]
* Session 3: link:presentations/Session_3_Polyglot_Persist.pptx[_Polyglot Persistence with Spring Data REST_]
** Lab 2: link:labs/lab02/lab02.adoc[Build a Hypermedia-Driven RESTful Web Service with Spring Data REST]
* Session 4: link:presentations/Session_4_Advanced_Boot.pptx[_Advancing Spring Boot with Actuator and Profiles_]
** Lab 3: link:labs/lab03/lab03.adoc[Enhancing Boot Application with Metrics]
* Session 5: link:presentations/Session_5_Intro_SC.pptx[_Introducing Spring Cloud Netflix_]
* Session 6: link:presentations/Session_6_SC_Config.pptx[_Spring Cloud Config_]
** Lab 4: link:labs/lab04/lab04.adoc[Introducing Spring Cloud into Boot Application]
* Session 7: link:presentations/Session_7_SC_Discovery_LB.pptx[_Spring Cloud Netflix - Service Discovery & Load Balancing_]
** Lab 5: link:labs/lab05/lab05.adoc[Microservice Service Discover and Load Balancing]
* Session 8: link:presentations/Session_8_Circuit_Breaker.pptx[_Spring Cloud Netflix - Circuit Breakers_]
** Lab 6: link:labs/lab06/lab06.adoc[Microservice Fault Tolerance with Circuit Breakers]

== Lab Setup

To build the applications in this workshop, you'll need a couple of things:

* https://help.github.com/articles/set-up-git/#setting-up-git[Git]
* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java JDK 8]
* Your favorite IDE or editor (e.g., http://www.eclipse.org[Eclipse] or https://spring.io/tools[Spring Tool Suite], https://www.jetbrains.com/idea[IntelliJ IDEA], https://netbeans.org[NetBeans], Visual Studio, etc)

We'll be pushing applications and creating services in Pivotal Cloud Foundry (PCF). This workshop uses Pivotal Web Services, an instance of PCF hosted by Pivotal.

* Login or signup for a free http://run.pivotal.io[Pivotal Web Services] account
* Click the _Tools_ link and...
** download and install the CLI matching your operating system
** login to the CF CLI (`cf login -a api.run.pivotal.io`)

== Clone repo

To follow along with the lab exercises, please clone this git repo on your local machine

[source,bash]
----
$ git clone https://github.com/Pivotal-Field-Engineering/CN-Workshop.git
----

== IDE Setup and tips

TIP: This section shares some optional tips for configuring your IDE for an optimal experience during the workshop!

=== Eclipse / Spring Tool Suite

Exclude `java.awt.*` from auto-complete suggestions::
`Preferences -> Java -> Appearance -> Type Filters -> Add... -> java.awt.*`
+
This way when you need to auto import something with `List` you don’t get the dialog box that asks if you want `java.awt.List` when you really want `java.util.List`

Configure Maven Auto Update::
`Preferences -> Maven -> {checkedbox} Automatically update Maven projects configuration`
+
Allows you to change a `pom.xml` and have the eclipse classpath automatically change without having to trigger the change manually.

Open pom.xml in XML view::
`Preferences -> Maven -> User Interface -> {checkedbox} Open XML Page in the POM editor by default`
+
This will get you straight to the XML when you first open your `pom.xml`

Show line numbers::
`Preferences -> General -> Editors -> Text Editors -> Show Line Numbers`
+
Very useful when collaborating and you need to explicitly state which line number you are referring to.

Automatically refresh resources changed outside of Eclipse::
`Preferences -> General -> Workspace -> Refresh using native hooks or profiling`
+
This enables Eclipse to recognize changes to files that have been modified outside of Eclipse. Pretty handy.


Close all views you don’t need::
Give yourself more space to view/write code by closing any views in the perspective that you don’t use, such as: Outline, Spring Explorer, and Servers

Boot Dashboard::
Use it, it’s awesome :)
