ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:spring-boot-version: 1.5.11

= Building a Spring Boot Application

== Overview

[.lead]
Spring Boot makes it easy to create stand-alone, production-grade Spring based Applications that you can "just run". We take an opinionated view of the Spring platform and third-party libraries so you can get started with minimum fuss. Most Spring Boot applications need very little Spring configuration.

== Create a Spring Boot Project

. Browse to https://start.spring.io[Spring Initializr]

. Generate a `Maven Project` with `Java` and Spring Boot `{spring-boot-version}`

. Fill out the *Project metadata* fields as follows:

Group:: io.pivotal
Artifact:: cloud-native-spring

. In the dependencies section, add each of the following manually:

- *Web*
- *Rest Repositories*
- *JPA*
- *H2*
- *Actuator*

. Click the _Generate Project_ button and your browser will download the `cloud-native-spring.zip` file.

. Copy then unpack the downloaded zip file to `CN-Workshop/labs/my_work/cloud-native-spring`
+
[source,bash]
----
CN-Workshop $ mkdir labs/my_work
CN-Workshop $ cd labs/my_work
CN-Workshop/labs/my_work $ cp ~/Downloads/cloud-native-spring.zip .
CN-Workshop/labs/my_work $ unzip cloud-native-spring.zip
CN-Workshop/labs/my_work $ cd cloud-native-spring
----
+
Your directory structure should now look like:
+
[source,bash]
----
CN-Workshop:
├── labs
│   ├── my_work
│   │   ├── cloud-native-spring
----

. Rename `application.properties` to `application.yml`
+
Spring Boot uses the `application.properties`/`application.yml` file to specify various properties which configure the behavior of your application.  By default, Spring Initializr (start.spring.io) creates a project with an `application.properties` file, however, throughout this workshop we will be https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml[using YAML instead of Properties].
+
[source,bash]
----
CN-Workshop/labs/my_work/cloud-native-spring $ mv src/main/resources/application.properties src/main/resources/application.yml
----


. Import the project’s pom.xml into your editor/IDE of choice.
+
[TIP]
====
*Spring Tool Suite Import Help*

Navigate to: `File -> Import… -> Maven -> Existing Maven Projects`

On the Import Maven Projects page, _Browse_ to: `CN-Workshop/labs/my_work/cloud-native-spring`
====

== Add an Endpoint

. Add an `@RestController` annotation to the class `CloudNativeSpringApplication`
+
.cloud-native-spring/src/main/java/io/pivotal/cloudnativespring/CloudNativeSpringApplication.java
[source,java,numbered]
----
package io.pivotal.cloudnativespring;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class CloudNativeSpringApplication {

    public static void main(String[] args) {
        SpringApplication.run(CloudNativeSpringApplication.class, args);
    }
}
----

. Add the following request handler to the class `CloudNativeSpringApplication`
+
.cloud-native-spring/src/main/java/io/pivotal/cloudnativespring/CloudNativeSpringApplication.java
[source,java,numbered]
----
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
----
+
Completed:
+
.cloud-native-spring/src/main/java/io/pivotal/cloudnativespring/CloudNativeSpringApplication.java
[source,java,numbered]
----
package io.pivotal.cloudnativespring;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class CloudNativeSpringApplication {

    public static void main(String[] args) {
        SpringApplication.run(CloudNativeSpringApplication.class, args);
    }

    @RequestMapping("/")
    public String hello() {
        return "Hello World!";
    }
}
----

== Run the _cloud-native-spring_ Application

. Run the application using the project's Maven Wrapper command:
+
[source,bash]
----
CN-Workshop/labs/my_work/cloud-native-spring $ ./mvnw spring-boot:run
----

. You should see the application start up an embedded Apache Tomcat server on port `8080` (review terminal output):
+
[source,log]
----
2017-11-01 21:41:09.949  INFO 19104 --- [main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-11-01 21:41:09.957  INFO 19104 --- [main] i.p.c.CloudNativeSpringApplication       : Started CloudNativeSpringApplication in 5.694 seconds (JVM running for 9.866)
----

. View your web application by browsing to http://localhost:8080
+
[NOTE]
====
Already have something running on port `8080`? You can tell Spring Boot to use a different port by specifying the Java System property `-Dserver.port=9999`

[source,bash]
----
./mvnw spring-boot:run -Dserver.port=9999
----
====

. After validating the app is running properly, stop the _cloud-native-spring_ application by pressing `CTRL + C` in the terminal window.

== Deploy _cloud-native-spring_ to Pivotal Cloud Foundry

. Build the application using the project's Maven Wrapper command
+
[source,bash]
----
CN-Workshop/labs/my_work/cloud-native-spring $ ./mvnw package
----

. Create a Cloud Foundry application manifest.
+
Defining a `manifest.yml` is a very useful way of specifying sensible defaults for your application when deploying to Cloud Foundry.
+
[source,bash]
----
CN-Workshop/labs/my_work/cloud-native-spring $ touch manifest.yml
----
+
Add application metadata, using a text editor (of choice)
+
[source,yaml]
----
---
applications:
- name: cloud-native-spring
  random-route: true
  memory: 768M
  path: target/cloud-native-spring-0.0.1-SNAPSHOT.jar
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
----

. Push application into Cloud Foundry
+
[source,log]
----
CN-Workshop/labs/my_work/cloud-native-spring $ cf push
Using manifest file /Users/someuser/git/CN-Workshop/labs/my_work/cloud-native-spring/manifest.yml
...
Showing health and status for app cloud-native-spring in org user-org / space user-space as user@example.com...
OK

requested state: started
instances: 1/1
usage: 768M x 1 instances
urls: cloud-native-spring-liqxfuds.cfapps.io
last uploaded: Thu Nov 2 03:33:23 UTC 2017
stack: cflinuxfs2
buildpack: java_buildpack

     state     since                    cpu    memory          disk           details
#0   running   2017-11-01 10:34:24 PM   0.0%   92.8M of 768M   152.6M of 1G
----

. Find the URL created for your app in the health status report (e.g., cloud-native-spring-<random>.cfapps.io) and browse to your app.
+

[TIP]
====
If you want to find out route of your applicaiton in future, you can run `cf routes` conmand to find out. It will show a table
----
CN-Workshop/labs/my_work/cloud-native-spring $ cf routes
Getting routes for org user-org / space user-space as user@example.com ...

space       host                          domain      port   path   type   apps                 
user-space  cloud-native-spring-liqxfuds  cfapps.io                        cloud-native-spring
----
====
*Congratulations!* You’ve just completed your first Spring Boot application. 

Lets proceed to link:../lab02/lab02.adoc[Lab 2] or back to link:../../README.adoc[Home]
