management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
        rsocket:
          enabled: true
          host: localhost
          port: 7171
          max-retries: 1000
          first-backoff: 10s
          max-backoff: 5m
